AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'todoable.gemspec'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'test/*_test.rb'
    - 'test/todoable/*_test.rb'